name: buildfork
permissions:
  contents: write
on: 
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Cache
        uses: actions/cache@v4.2.3
        with: 
          path: ~/.npm
          key: buildCache
      - run: npm ci
      - run: npm test -- --coverage
        env: 
          CI: true
      - name: Upload code coverage
        uses: actions/upload-artifact@v4.6.2
        with: 
          name: codecoverage
          path: coverage
      - name: build
        run: npm run build
      - name: Upload build files
        uses: actions/upload-artifact@v4.6.2
        with: 
          name: build
          path: build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: http://hurried-earthquake.surge.sh
    steps:
      - name: Download the Build Artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: build
      - name: deploy to surge
        run: npx surge --project ‘/home/runner/work/exer4-test/exer4-test’ --domain http://hurried-earthquake.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
